FROM node:16.14-alpine as build 
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Copying the files to the folder
ENV PATH /frontend/node_modules/.bin:$PATH
COPY /frontend/package.json .
COPY /frontend/package-lock.json .
# Build app
COPY /frontend/. .
RUN npm install
COPY . .
RUN npm run build

# Copy build to nginx
FROM nginx:latest
COPY --from=build /usr/src/app/build /usr/share/nginx/html
WORKDIR /etc/nginx/conf.d
COPY default.conf default.conf
EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]